@Restaurants.API_HostAddress = https://localhost:7111
@token = CfDJ8AzoK4A7VhVMt2mx8fu3m17g9vZzG86uWVuS_1gw3zjhkhohmz9w72hd_hBO1ro3QT96dgmS7ou2TCMCLmKbjpmI96uoKcDfi8KnM0h5tIyKUg7ST-6ROrVyoDH0YsYheJsiXqn1qxZ171i6-HRUU-IOfx9ICD9ImCX4xvrLVKZSPTkSuxEggOLW8PE9wTATZqmagkS9Elj1u0gMRIdIJv-NzPt-foOK186mesLBj76DaTHYW-kAp0q4W-RjCIP0IB774VBf0AZeG9krl03_aR-aBqLaWCFBOPgCu_pTS2q8_KZCXlwiiH8kem-7vscA2CHM7_6FBql4_R85-q0Y2SFhWe-6D5tbtEdf_r5RGlxIJLnH8PA9Fj0pFiJjRfwlE_hiONe8kvn5kMTgPNeTz11oiP7-4ARRtqh8MWP87bi610FQVV0pNs5sbwZMpmiBajMlkhGwKKYPWSSw7Gi6fGK1PIfsjByPmv96hN2QwlOxYuS1NXewHzByhNLiios02ImuaH0UqZfleJ1dh6Q2E4PrYdMqqQteonpbShyuOO7tMfgUlmbxhsfog7fGGr5E2OCjAxqetQQZ0nAiilb0AwIubO3--HmoNmRS3mUHL59rT0F5ovCi38ds3XMNvSrbF5lmDdUKwHkz7v2HCHBx_LYQhIUqaG8uNzxYkrpw99O2HsuZ23V2HHkAmSyphulRHAUHMJDzbw2F66l0RUIMmBdEpCfeZp1msqmU6IS9Km-G-dzrTzEVo3EZIwl0rMHZlpwP59wRMR002YKm9_ss9_KZFU05itUlibOkO2utBdEQxR8B9O-_65S_iwIzbE2JCgC0BsbRtsKbx7FWz8kHIBfCACX-mO44UxmjyuYTVdtLXrLm4--iaVbCpKD9KeZ70Q

GET {{Restaurants.API_HostAddress}}/api/restaurants
# Authorization: Bearer {{token}}
###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3
Authorization: Bearer {{token}}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/7

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json
Authorization: Bearer {{token}} 
{
  "name": "Owner restaurant ",
  "Description": "A cozy restaurant experience like no other",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "info@gourmetdelights.com",
  "ContactNumber": "555-123-4567",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "10-010"
}

###
GET https://localhost:7111/api/Restaurants/9

###
PATCH {{Restaurants.API_HostAddress}}/api/restaurants/6
Content-Type: application/json

{
   "name": "Spicy testtesttesttest test",
  "Description": "A culinary experience like no other",
  "HasDelivery": true
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Content-Type: application/json

{
    "name": "Spicy Chicken Curry",
    "description": "A fiery blend of spices with tender chicken pieces",
    "price": 12.99,
    "KiloCalroies": 750
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Authorization : Bearer {{token}}
###


DELETE {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email":"user@test.com",
    "password":"Password1!"
}

###
POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email":"owner@test.com",
    "password":"Password1!"
}

###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "Nationality": "French",
  "DateOfBirth":"2010-01-01"
}

###
