@Restaurants.API_HostAddress = https://localhost:7111


GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/7

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "name": "tasty test test test",
  "Description": "A culinary experience like no other",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "info@gourmetdelights.com",
  "ContactNumber": "555-123-4567",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "10-010"
}

###
GET https://localhost:7111/api/Restaurants/1

###
PATCH {{Restaurants.API_HostAddress}}/api/restaurants/6
Content-Type: application/json

{
   "name": "Spicy testtesttesttest test",
  "Description": "A culinary experience like no other",
  "HasDelivery": true
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Content-Type: application/json

{
    "name": "Spicy Chicken Curry",
    "description": "A fiery blend of spices with tender chicken pieces",
    "price": 12.99,
    "KiloCalroies": 750
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes

###


DELETE {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes

###

